### ISSUE TITLE
Get device name

### ISSUE THREAD

**Issue by minoskt** [nbuchwitz/python3-uhubctl#23]
This python wrapper is working really well.
I think what is missing is a way to get the device name that is connected to a particular port.

e.g.,
`Port 4: 0303 power lowspeed enable connect [04d9:0007 Raspberry Pi Internal Keyboard]`

Is it possible to add this? Thank you in advance.

**Comment by nbuchwitz** [comment]
Please checkout #24

**Comment by nbuchwitz** [comment]
@minoskt any chance that you could test the linked PR with the feature you're were requesting?

**Comment by minoskt** [comment]
Thank you @nbuchwitz. I can confirm it is working very well!
Thanks and sorry for the delay.
