### ISSUE TITLE
FYI: I wrote something similar

### ISSUE THREAD

**Issue by hmaerki** [nbuchwitz/python3-uhubctl#25]
Hi Nicolai

I saw your [python3-uhubctl](https://github.com/nbuchwitz/python3-uhubctl) and I like it.

I wrote something similiar (still work in progress): [pyhubctl](https://github.com/octoprobe/pyhubctl). Any feedback is welcome.

Kind regards, Hans

**Comment by nbuchwitz** [comment]
Hi Hans, thanks for your kind works and letting me know about your project. I will take a look.
